// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Manager.Models;

public partial class Material
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Amount { get; set; }

    public bool? Acquired { get; set; }

    public int? ProjectId { get; set; }

    public virtual Project Project { get; set; }
}