// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project_Manager.Models;

public partial class Project
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? UserId { get; set; }

    public string Description { get; set; }

    public int? StatusId { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string BeforeImage { get; set; }

    public string AfterImage { get; set; }

    public string Sketch { get; set; }

    public string PatternLink { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Material> Material { get; set; } = new List<Material>();

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}